FROM crossbario/autobahn-python:cpy3

RUN apt-get update && apt-get install -y \
  python3 \
  postgresql-server-dev-all \
  python3-pip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 install inject psycopg2 dateutils python-redmine

ENV TZ=America/Argentina/Buenos_Aires
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY src /src
COPY run.sh /src/
WORKDIR /src

CMD ["sh","/src/run.sh"]
